
BEGIN;

DROP TABLE IF EXISTS "user", "product", "category", "function", "place", "product_has_category", "product_has_place";

CREATE TABLE IF NOT EXISTS "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstname" VARCHAR(255) NOT NULL,
    "lastname" VARCHAR(255) NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT Now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "function" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT Now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "category" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT Now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "place" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT Now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "product" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "user_id" INT NOT NULL REFERENCES "user" ("id"),
    "function_id" INT NOT NULL REFERENCES "function" ("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT Now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "product_has_category" (
    "product_id" INT NOT NULL REFERENCES "product" ("id"),
    "category_id" INT NOT NULL REFERENCES "category" ("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT Now(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "product_has_place" (
    "product_id" INT NOT NULL REFERENCES "product" ("id"),
    "place_id" INT NOT NULL REFERENCES "place" ("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT Now(),
    "updated_at" TIMESTAMPTZ
);

COMMIT;